language: csharp
solution: src/NzbDrone.sln
addons:
  apt:
    packages:
      - nodejs
      - npm
script:
  - ./build.sh
  - chmod +x test.sh
#  - ./test.sh Linux Unit Takes far too long, maybe even crashes travis :/
after_success:
  - chmod +x package.sh
  - ./package.sh
notifications:
  - webhooks: https://discordapp.com/api/webhooks/266910310219251712/V-QvCcnYkg3O8PMevcAJOJyCgrYkZQoF2pupLDGbaISNUECmYPd6LRwl3avKHsPyfgWP
