version: '0.2.0.{build}'

image: Visual Studio 2017

assembly_info:
  patch: true
  file: 'src\NzbDrone.Common\Properties\SharedAssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-rc1'

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

install:
  - git submodule update --init --recursive
  
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
  - ps: ./build-appveyor.ps1

test: off
#test:
#  assemblies:
#    - '_tests\*Test.dll'
#  categories:
#    except:
#      - IntegrationTest
#      - AutomationTest

artifacts:
  - path: '_artifacts\*.zip'
  - path: '_artifacts\*.exe'
  - path: '_artifacts\*.tar.gz'

cache:
  - '%USERPROFILE%\.nuget\packages'
  - node_modules -> package.json
  
pull_requests:
  do_not_increment_build_number: true

on_failure:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - ps: Get-ChildItem .\_artifacts\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem .\_artifacts\*.exe | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem .\_artifacts\*.tar.gz | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

only_commits:
  files:
    - src/
    - osx/
    - gulp/
    - logo/
    - setup/
    - appveyor.yml
    - build-appveyor.cake

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))