version: '0.5.0.{build}'

image: Previous Visual Studio 2017

assembly_info:
  patch: true
  file: 'src\NzbDrone.Common\Properties\SharedAssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-rc1'

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  nodejs_version: "8"

install:
  - git submodule update --init --recursive
  - ps: Install-Product node $env:nodejs_version

build_script:
  - C:\msys64\usr\bin\bash -lc "cd \"$APPVEYOR_BUILD_FOLDER\" && exec ./build.sh
  
after_build:
  - C:\msys64\usr\bin\bash -lc "cd \"$APPVEYOR_BUILD_FOLDER\" && exec ./appveyor-package.sh
  - ps: Get-ChildItem .\_artifacts\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem .\_artifacts\*.exe | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem .\_artifacts\*.tar.gz | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

test_script:
  - node --version
  - yarn --version
  - C:\msys64\usr\bin\bash -lc "cd \"$APPVEYOR_BUILD_FOLDER\" && exec ./test.sh Windows Unit

cache:
  - '%USERPROFILE%\.nuget\packages'
  - node_modules -> package.json
  
pull_requests:
  do_not_increment_build_number: true

skip_branch_with_pr: true

on_failure:
  - ps: Get-ChildItem .\_artifacts\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem .\_artifacts\*.exe | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem .\_artifacts\*.tar.gz | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

only_commits:
  files:
    - src/
    - osx/
    - gulp/
    - logo/
    - setup/
    - frontend/
    - appveyor.yml
    - build.sh
    - test.sh
    - package.json
    - appveyor-package.sh
