version: '0.6.1.{build}'

image:
  - Visual Studio 2017
  - Ubuntu1804

assembly_info:
  patch: true
  file: 'src\NzbDrone.Common\Properties\SharedAssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-rc1'

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  nodejs_version: "10"
  SENTRY_AUTH_TOKEN:
    secure: dIzaGkyqP8JefC+GyXH2RtBHCufpzegoJnxvwGenCsMZNgaVbnoNo4ZMnPY2WYpstCcdXmZb7hbPYmu4FRkKQ8xDQ34YNGlKRKnlFuOQoq8=
  SENTRY_ORG: "lidarr"

install:
  - git submodule update --init --recursive
  - cmd: powershell Install-Product node $env:nodejs_version
  - sh: nvm install $nodejs_version
  - sh: sudo apt update
  - sh: sudo apt install -y libchromaprint-tools

build_script:
  - cmd: C:\msys64\usr\bin\bash -lc "cd \"$APPVEYOR_BUILD_FOLDER\" && exec ./build.sh
  - sh: ./build.sh
  
after_build:
  - cmd: C:\msys64\usr\bin\bash -lc "cd \"$APPVEYOR_BUILD_FOLDER\" && exec ./appveyor-package.sh
  - sh: ./appveyor-package.sh
  - ps: Get-ChildItem .\_artifacts\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem .\_artifacts\*.exe | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem .\_artifacts\*.tar.gz | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

test_script:
  - node --version
  - yarn --version
  - cmd: C:\msys64\usr\bin\bash -lc "cd \"$APPVEYOR_BUILD_FOLDER\" && exec ./test.sh Windows Unit
  - sh: ./test.sh Linux Unit
  - sh: find "$APPVEYOR_BUILD_FOLDER" -type f -name 'myresults.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/nunit3/$APPVEYOR_JOB_ID"

cache:
  - node_modules -> package.json
  
pull_requests:
  do_not_increment_build_number: true

skip_branch_with_pr: true

on_failure:
  - ps: Get-ChildItem .\_artifacts\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem .\_artifacts\*.exe | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem .\_artifacts\*.tar.gz | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

only_commits:
  files:
    - src/
    - osx/
    - gulp/
    - logo/
    - setup/
    - frontend/
    - appveyor.yml
    - build.sh
    - test.sh
    - package.json
    - appveyor-package.sh
