name: 'Support requests'

on:
  issues:
    types: [labeled, unlabeled, reopened]

permissions: {}
jobs:
  support:
    permissions:
      issues: write # to modify issues

    runs-on: ubuntu-latest
    steps:
      - uses: dessant/support-requests@v3
        with:
          github-token: ${{ github.token }}
          support-label: 'Type: Support'
          issue-comment: >
            :wave: @{issue-author}, we use the issue tracker exclusively
            for bug reports and feature requests. However, this issue appears
            to be a support request. Please hop over onto our [Discord](https://radarr.video/discord).
          close-issue: true
          close-reason: 'not planned'
          lock-issue: false
      - uses: dessant/support-requests@v3
        with:
          github-token: ${{ github.token }}
          support-label: 'Status: Logs Needed'
          issue-comment: >
            :wave: @{issue-author}, In order to help you further we'll need to see logs. 
            You'll need to enable trace logging and replicate the problem that you encountered. 
            Guidance on how to enable trace logging can be found in 
            our [troubleshooting guide](https://wiki.servarr.com/radarr/troubleshooting#logging-and-log-files).
          close-issue: false
          lock-issue: false
